// Generated by gencpp from file mynt_eye_ros_wrapper/GetInfo.msg
// DO NOT EDIT!


#ifndef MYNT_EYE_ROS_WRAPPER_MESSAGE_GETINFO_H
#define MYNT_EYE_ROS_WRAPPER_MESSAGE_GETINFO_H

#include <ros/service_traits.h>


#include "GetInfoRequest.h"
#include "GetInfoResponse.h"


namespace mynt_eye_ros_wrapper
{

struct GetInfo
{

typedef GetInfoRequest Request;
typedef GetInfoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetInfo
} // namespace mynt_eye_ros_wrapper


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mynt_eye_ros_wrapper::GetInfo > {
  static const char* value()
  {
    return "422c950b17bb0d86a2478389576d7ab5";
  }

  static const char* value(const ::mynt_eye_ros_wrapper::GetInfo&) { return value(); }
};

template<>
struct DataType< ::mynt_eye_ros_wrapper::GetInfo > {
  static const char* value()
  {
    return "mynt_eye_ros_wrapper/GetInfo";
  }

  static const char* value(const ::mynt_eye_ros_wrapper::GetInfo&) { return value(); }
};


// service_traits::MD5Sum< ::mynt_eye_ros_wrapper::GetInfoRequest> should match 
// service_traits::MD5Sum< ::mynt_eye_ros_wrapper::GetInfo > 
template<>
struct MD5Sum< ::mynt_eye_ros_wrapper::GetInfoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mynt_eye_ros_wrapper::GetInfo >::value();
  }
  static const char* value(const ::mynt_eye_ros_wrapper::GetInfoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mynt_eye_ros_wrapper::GetInfoRequest> should match 
// service_traits::DataType< ::mynt_eye_ros_wrapper::GetInfo > 
template<>
struct DataType< ::mynt_eye_ros_wrapper::GetInfoRequest>
{
  static const char* value()
  {
    return DataType< ::mynt_eye_ros_wrapper::GetInfo >::value();
  }
  static const char* value(const ::mynt_eye_ros_wrapper::GetInfoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mynt_eye_ros_wrapper::GetInfoResponse> should match 
// service_traits::MD5Sum< ::mynt_eye_ros_wrapper::GetInfo > 
template<>
struct MD5Sum< ::mynt_eye_ros_wrapper::GetInfoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mynt_eye_ros_wrapper::GetInfo >::value();
  }
  static const char* value(const ::mynt_eye_ros_wrapper::GetInfoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mynt_eye_ros_wrapper::GetInfoResponse> should match 
// service_traits::DataType< ::mynt_eye_ros_wrapper::GetInfo > 
template<>
struct DataType< ::mynt_eye_ros_wrapper::GetInfoResponse>
{
  static const char* value()
  {
    return DataType< ::mynt_eye_ros_wrapper::GetInfo >::value();
  }
  static const char* value(const ::mynt_eye_ros_wrapper::GetInfoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MYNT_EYE_ROS_WRAPPER_MESSAGE_GETINFO_H
