// Generated by gencpp from file mynt_eye_ros_wrapper/GetInfoResponse.msg
// DO NOT EDIT!


#ifndef MYNT_EYE_ROS_WRAPPER_MESSAGE_GETINFORESPONSE_H
#define MYNT_EYE_ROS_WRAPPER_MESSAGE_GETINFORESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mynt_eye_ros_wrapper
{
template <class ContainerAllocator>
struct GetInfoResponse_
{
  typedef GetInfoResponse_<ContainerAllocator> Type;

  GetInfoResponse_()
    : value()  {
    }
  GetInfoResponse_(const ContainerAllocator& _alloc)
    : value(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::mynt_eye_ros_wrapper::GetInfoResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mynt_eye_ros_wrapper::GetInfoResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetInfoResponse_

typedef ::mynt_eye_ros_wrapper::GetInfoResponse_<std::allocator<void> > GetInfoResponse;

typedef boost::shared_ptr< ::mynt_eye_ros_wrapper::GetInfoResponse > GetInfoResponsePtr;
typedef boost::shared_ptr< ::mynt_eye_ros_wrapper::GetInfoResponse const> GetInfoResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mynt_eye_ros_wrapper::GetInfoResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mynt_eye_ros_wrapper::GetInfoResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mynt_eye_ros_wrapper

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mynt_eye_ros_wrapper::GetInfoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mynt_eye_ros_wrapper::GetInfoResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mynt_eye_ros_wrapper::GetInfoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mynt_eye_ros_wrapper::GetInfoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mynt_eye_ros_wrapper::GetInfoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mynt_eye_ros_wrapper::GetInfoResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mynt_eye_ros_wrapper::GetInfoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "64e58419496c7248b4ef25731f88b8c3";
  }

  static const char* value(const ::mynt_eye_ros_wrapper::GetInfoResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x64e58419496c7248ULL;
  static const uint64_t static_value2 = 0xb4ef25731f88b8c3ULL;
};

template<class ContainerAllocator>
struct DataType< ::mynt_eye_ros_wrapper::GetInfoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mynt_eye_ros_wrapper/GetInfoResponse";
  }

  static const char* value(const ::mynt_eye_ros_wrapper::GetInfoResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mynt_eye_ros_wrapper::GetInfoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string value\n\
\n\
";
  }

  static const char* value(const ::mynt_eye_ros_wrapper::GetInfoResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mynt_eye_ros_wrapper::GetInfoResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetInfoResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mynt_eye_ros_wrapper::GetInfoResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mynt_eye_ros_wrapper::GetInfoResponse_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MYNT_EYE_ROS_WRAPPER_MESSAGE_GETINFORESPONSE_H
